#!/usr/bin/env python3
"""Regenerate architecture.data.js and pulse.data.js from their JSON sources.

Single sources of truth:
  architecture.json — slow-changing structure (hand-edited)
  pulse.json        — fast-changing state (hand-edited, with auto-filled git block)

File layout in this folder:
  architecture.html       — shell only
  architecture.css        — extracted styles, hand-edited
  architecture.js         — render logic, hand-edited
  architecture.data.js    — AUTOGEN by this script (window.ARCH_DATA = ...)
  architecture.json       — hand-edited
  pulse.data.js           — AUTOGEN by this script (window.PULSE_DATA = ...)
  pulse.json              — hand-edited; `git` block auto-filled from `git log`
  build.py                — this script

All data assets are loaded via <script src>, which works on file://
(plain fetch('*.json') is blocked by file:// CORS in Chrome/Firefox).

Run after editing either JSON:

    python architecture/build.py

The .data.js files are generated; do not hand-edit them.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import date, datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent  # most projects: architecture/ sits one level below project root

ARCH_JSON = HERE / "architecture.json"
ARCH_JS = HERE / "architecture.data.js"
PULSE_JSON = HERE / "pulse.json"
PULSE_JS = HERE / "pulse.data.js"

BANNER = (
    "// AUTOGENERATED by architecture/build.py.\n"
    "// Edit the source JSON, then re-run: python architecture/build.py\n"
)
COMMIT_WINDOW = 14  # days of recent commits to include


def find_git_root(start: Path) -> Path | None:
    """Walk up from `start` looking for a .git directory. Returns None if not found."""
    cur = start.resolve()
    for p in [cur, *cur.parents]:
        if (p / ".git").exists():
            return p
    return None


def git(*args: str, cwd: Path) -> str:
    """Run git with the given args. Returns stdout (empty string on failure)."""
    try:
        out = subprocess.run(
            ["git", *args], cwd=str(cwd), capture_output=True, text=True, check=False
        )
        return out.stdout.strip() if out.returncode == 0 else ""
    except FileNotFoundError:
        return ""


def gather_git_block(repo_root: Path) -> dict | None:
    """Build the auto-filled `git` block for pulse.json. None if not a git repo."""
    if not (repo_root / ".git").exists():
        return None

    branch = git("rev-parse", "--abbrev-ref", "HEAD", cwd=repo_root) or None
    last_commit_date = git("log", "-1", "--format=%cs", cwd=repo_root) or None
    last_commit_sha = git("log", "-1", "--format=%h", cwd=repo_root) or None
    last_commit_subject = git("log", "-1", "--format=%s", cwd=repo_root) or None

    freshness_days: int | None = None
    if last_commit_date:
        try:
            freshness_days = (date.today() - datetime.strptime(last_commit_date, "%Y-%m-%d").date()).days
        except ValueError:
            freshness_days = None

    dirty_out = git("status", "--porcelain", cwd=repo_root)
    dirty = bool(dirty_out.strip())

    log_out = git(
        "log",
        f"--since={COMMIT_WINDOW}.days.ago",
        "--format=%cs%x09%h%x09%an%x09%s",
        "-n", "14",
        cwd=repo_root,
    )
    recent = []
    for line in log_out.splitlines():
        parts = line.split("\t", 3)
        if len(parts) == 4:
            d, sha, author, subject = parts
            recent.append({"date": d, "sha": sha, "author": author, "subject": subject})

    return {
        "branch": branch,
        "last_commit_date": last_commit_date,
        "last_commit_sha": last_commit_sha,
        "last_commit_subject": last_commit_subject,
        "freshness_days": freshness_days,
        "dirty": dirty,
        "recent_commits": recent,
    }


def write_data_js(out_path: Path, var_name: str, data: dict) -> None:
    payload = json.dumps(data, indent=2, ensure_ascii=False)
    out_path.write_text(f"{BANNER}window.{var_name} = {payload};\n", encoding="utf-8")
    rel = out_path.relative_to(out_path.parent.parent)
    print(f"wrote {rel} ({out_path.stat().st_size:,} bytes)")


def main() -> int:
    if not ARCH_JSON.exists() and not PULSE_JSON.exists():
        print(f"missing both: {ARCH_JSON} and {PULSE_JSON}", file=sys.stderr)
        return 1

    if ARCH_JSON.exists():
        arch = json.loads(ARCH_JSON.read_text(encoding="utf-8"))
        write_data_js(ARCH_JS, "ARCH_DATA", arch)
    else:
        print(f"skip: no {ARCH_JSON.name}", file=sys.stderr)

    if PULSE_JSON.exists():
        pulse = json.loads(PULSE_JSON.read_text(encoding="utf-8"))
        repo_root = find_git_root(HERE)
        if repo_root is not None:
            pulse["git"] = gather_git_block(repo_root)
        else:
            pulse.pop("git", None)
        write_data_js(PULSE_JS, "PULSE_DATA", pulse)
    else:
        print(f"skip: no {PULSE_JSON.name}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
