// AUTOGENERATED by architecture/build.py.
// Edit the source JSON, then re-run: python architecture/build.py
window.PULSE_DATA = {
  "project": "palmwtc",
  "updated": "2026-05-17",
  "status": {
    "phase": "v0.4.3",
    "phase_label": "PyPI library, stable (released; chamber-illustration docs branch open)",
    "percent_done": 90,
    "one_liner": "Released 0.4.3 (metadata cleanup — PyPI Author display fix per CHANGELOG 7.1). CI green since PRs #34/#35 (2026-04-29). Branch docs/chamber-illustration-with-sensor-detail open with sensor-pole + soil-sensor detail."
  },
  "blockers": [],
  "next_milestone": {
    "label": "Merge chamber-illustration docs PR; cut 0.4.4 if substantive",
    "target_date": "2026-05-25"
  },
  "decisions": [
    {
      "date": "2026-04-29",
      "decision": "Close ruff CI red via per-file-ignores (notebooks) + ruff format sweep (PR #34 + #35)",
      "why": "Long-standing red was blocking routine merges; mypy stays continue-on-error (warn-only)"
    },
    {
      "date": "2026-04-28",
      "decision": "Strip Co-Authored-By: Claude trailers from history via git filter-branch + force-push",
      "why": "Owner wants GitHub Contributors panel to show only their account; 9 commits affected, backup at backup/pre-claude-cleanup-20260428"
    },
    {
      "date": "2026-04-25",
      "decision": "Move under flux_chamber/ umbrella (cutover 2026-04-24)",
      "why": "Three-repo consolidation; palmwtc/.venv rebuilt with uv sync to fix stale absolute paths from editable-install"
    }
  ],
  "in_flight": [
    {
      "text": "Chamber illustration with sensor-pole + soil-sensor detail",
      "kind": "docs",
      "branch": "docs/chamber-illustration-with-sensor-detail"
    }
  ],
  "test_status": {
    "command": "unset VIRTUAL_ENV && uv run pytest",
    "pass": null,
    "fail": 0,
    "skip": null,
    "last_run": "2026-04-29"
  },
  "links": {
    "claude_md": "CLAUDE.md",
    "project_pulse": "docs/PROJECT_PULSE.md",
    "pyproject": "pyproject.toml",
    "umbrella_claude_md": "../CLAUDE.md"
  },
  "tags": [
    "public",
    "pypi",
    "mit",
    "library",
    "flux-chamber"
  ],
  "git": {
    "branch": "docs/chamber-illustration-with-sensor-detail",
    "last_commit_date": "2026-05-13",
    "last_commit_sha": "dacaf1c",
    "last_commit_subject": "docs: upgrade chamber illustration with sensor-pole + soil-sensor detail",
    "freshness_days": 6,
    "dirty": true,
    "recent_commits": [
      {
        "date": "2026-05-13",
        "sha": "dacaf1c",
        "author": "Didi Adisaputro",
        "subject": "docs: upgrade chamber illustration with sensor-pole + soil-sensor detail"
      }
    ]
  }
};
